Move English translation to separate directory and fix blog urls
qubistlabs/jibrel-website-v2 pull request #190
Opened 2019-09-24 18:39 UTC by stcherenkov

2019-09-25 07:32 UTC, Dragonesis approved these changes

2019-09-25 16:06 UTC, stcherenkov commented on .vuepress/src/components/base/MainHeader/SelectLanguage/SelectLanguage.vue
> +      console.log(lang);
console.log

2019-09-25 16:07 UTC, stcherenkov commented on .vuepress/theme/layouts/Layout.vue
> +      // vueRouter: this.$router,
Зачем он закомментирован тут? Может быть эту строку надо удалить, если она не используется?

2019-09-25 17:22 UTC, soar requested changes

2019-09-25 17:22 UTC, soar commented on nginx.tpl.conf
> +            return 302 $scheme://$http_host/$lang/;
```suggestion
            return 302 $scheme://$host/$lang/;
```
In the downstream container, you will always have a port number in this variable. You shouldn't use it in redirects.

2019-09-25 17:22 UTC, soar commented on nginx.tpl.conf
> +            return 301 $scheme://$http_host/$lang$request_uri;
```suggestion
            return 301 $scheme://$host/$lang$request_uri;
```
Same problem

2019-09-25 18:35 UTC, soar commented on nginx.tpl.conf
>          listen 80 default_server;
```suggestion
        listen 80 default_server;
        
        port_in_redirect off;
```
See https://github.com/jibrelnetwork/coinmena-web/pull/131

2019-09-26 11:03 UTC, soar commented on nginx.tpl.conf
> +            return 301 $scheme://$host/$lang$request_uri;
Maybe it's a bad idea to use permanent redirect with a variable?

2019-09-26 12:32 UTC, stcherenkov commented on nginx.tpl.conf
> +            return 301 $scheme://$host/$lang$request_uri;
Fixed!

2019-09-26 12:39 UTC, merged